apiVersion: v1
kind: Service
metadata:
  name: service-apache-server
spec:
  type: NodePort
  selector:
    app: apache-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
